---
title: "Dados da UG"
editor: visual
lang: "pt"
format:
  pdf: default
  html:
    code-fold: true
    code-summary: "mostrar o código"
    code-overflow: wrap
execute:
  warning: false
  message: false
  error: false
  cache: refresh
  freeze: auto
  echo: false
---

```{r}
#| warning: false
#| message: false
#| error: false
library(readxl)
library(tidyverse)
library(leaflet)
library(janitor)
library(lubridate)
library(tidyverse)
library(purrr)
library(knitr)
library(kableExtra)
library(DescTools)
library(zoo)
library(stringr)
library(data.table)
library(DT)
library(readr)
```

```{r}
`%notin%` <- Negate(`%in%`)

# formato dos numeros
myNumFmt <- as.fmt(digits=0, big.mark=".")

options(scipen = 999)
```

```{r}
lista_ugs_gestor <- read_excel("lista_ugs_gestor.xlsx") %>% clean_names()
```

```{r}
# ug_selecionada <-  "070015"

ug_selecionada <- read_csv("ug_selecionada.csv")$ug_selecionada
```

## Dados da UG

### Nome e local

```{r}
lista_ugs_gestor %>% 
  filter(ug_executora_codigo == ug_selecionada) %>%
  select( ug_executora_nome, ug_executora_codigo, 
          uge_municipio_nome, uge_uf_sigla) %>% 
  pivot_longer( cols = everything()) %>% mutate(name = str_remove(name,"ug_"), name = str_remove(name,"executora"),name = str_remove(name,"uge"), name =str_to_upper(  str_replace_all(name,"_"," ")))%>% kable(col.names = c("Item", "Resultado"))
```

### Rol de responsáveis

```{r}
lista_ugs_gestor %>%
  filter(ug_executora_codigo == ug_selecionada) %>%
  select(uge_assinatura_ne_responsavel_nome,
         uge_assinatura_ne_substituto_nome,
         uge_conf_documental_responsavel_nome,
         uge_conf_documental_substituto_nome,
         uge_contador_responsavel_nome,
         uge_contador_substituto_nome,
         uge_fechamento_lc_responsavel_nome,
         uge_fechamento_lc_substituto_nome,
         uge_gestor_financeiro_responsavel_nome,
         uge_gestor_financeiro_substituto_nome,
         uge_inscricao_ne_rp_responsavel_nome,
         uge_inscricao_ne_rp_substituto_nome,
         uge_ordenador_responsavel_nome,
         uge_ordenador_substituto_nome)   %>%
  pivot_longer( cols = everything())%>% 
  mutate (value =  str_extract(value, regex("[A-Z]*")),
          name = str_sub(name, start = 4L, end= -5L),
          name =str_to_upper(  str_replace_all(name,"_"," ")) )%>%
  kable(col.names =c( "Atribuição","Responsáveis"))
```

### Hierarquia organizacional

```{r}
lista_ugs_gestor %>% 
  filter(ug_executora_codigo == ug_selecionada) %>%
  select( orgao_uge_nome,
          orgao_uge_orgao_superior_nome, 
          orgao_uge_orgao_maximo_nome,
          uge_ug_setorial_financeira_nome, 
          uge_ug_setorial_financeira_codigo,
          uge_ug_setorial_orcamentaria_nome, 
          uge_ug_setorial_orcamentaria_codigo) %>%
  pivot_longer( cols = everything())%>% mutate(name = str_remove(name,"uge_"),
          name =str_to_upper(  str_replace_all(name,"_"," "))) %>% kable(col.names = c("Item","Resultado"))
```

### Opções sobre a execução orçamentária e centro de custos

```{r}
lista_ugs_gestor %>% filter(ug_executora_codigo == ug_selecionada) %>%
  select(orgao_uge_detalhamento_credito,
         orgao_uge_utiliza_pi_s_n,
         orgao_uge_usa_centro_custo_s_n ) %>%
  pivot_longer( cols = everything())%>% mutate(name = str_remove(name,"orgao_uge_"),
          name =str_to_upper( str_replace_all(name,"_"," ")) )%>% kable(col.names = c("Regras","Opção"))
```
