---
title: "Documentos emitidos"
editor: visual
lang: "pt"
format:
  # pdf: default
  html:
    code-fold: true
    code-summary: "mostrar o código"
    code-overflow: wrap
execute:
  warning: false
  message: false
  error: false
  cache: refresh
  freeze: auto
  # echo: false
---

```{r}
#| warning: false
#| message: false
#| error: false
library(readxl)
library(tidyverse)
library(leaflet)
library(janitor)
library(lubridate)
library(tidyverse)
library(purrr)
library(knitr)
library(kableExtra)
library(DescTools)
library(zoo)
library(stringr)
library(data.table)
library(DT)
library(readr)
```

```{r}
`%notin%` <- Negate(`%in%`)

# formato dos numeros
myNumFmt <- as.fmt(digits=0, big.mark=".")

options(scipen = 999)
```

```{r}
lista_ugs_gestor <- read_excel("lista_ugs_gestor.xlsx") %>% clean_names()
```

```{r}
# ug_selecionada <-  "070015"

ug_selecionada <- read_csv("ug_selecionada.csv") $ug_selecionada
```

```{r}
docs_ug <- read_excel(paste0("docs_ug_",ug_selecionada,".xlsx")) %>%
            clean_names()
```

## Documentos emitidos

### Quantitativo por tipo de documento

```{r}
docs_ug %>% group_by(doc_tipo_nome) %>% count() %>% arrange(desc(n)) %>%
            kable(col.names = c("Tipo de documento","Quantidade") ,digits = 0, format.args = list(big.mark = ".", decimal.mark = ","))
```

### Qual operador emitiu o documento

```{r}
docs_ug %>% group_by(doc_lancado_por_nome ) %>% 
  mutate(doc_lancado_por_nome = 
        str_extract(doc_lancado_por_nome, regex("[A-Z]*"))) %>%
  count() %>% arrange(desc(n)) %>% kable(col.names = c("Operador","Quantidade") ,digits = 0, format.args = list(big.mark = ".", decimal.mark = ","))
```

```{r}
#| eval: false
docs_ug %>% group_by(doc_tipo_codigo,doc_lancado_por_nome  ) %>%
  mutate(doc_lancado_por_nome =
          str_extract(doc_lancado_por_nome, regex("[A-Z]*"))) %>%
  count()  %>% kable(digits = 0, format.args = list(big.mark = ".", decimal.mark = ","))
```

### Tipo de favorecido: quantitativo

```{r}
docs_ug %>% group_by(favorecido_tipo_nome ) %>% count() %>%
            arrange(desc(n)) %>% head(20) %>% kable(col.names = c("Tipo de favorecido","Quantidade") ,digits = 0, format.args = list(big.mark = ".", decimal.mark = ","))
```

### Principais UGs favorecidas

```{r}
docs_ug %>% filter(favorecido_tipo_nome == "UNIDADE GESTORA") %>%
            group_by(favorecido_doc_nome ) %>% count() %>%
            arrange(desc(n)) %>% head(20)%>% kable(col.names = c("Favorecido","Quantidade") ,digits = 0, format.args = list(big.mark = ".", decimal.mark = ","))
```

### Favorecidos e tipos de documentos

```{r}
docs_ug %>% filter(doc_tipo_codigo != "NS") %>%
            group_by( favorecido_doc_nome, doc_tipo_codigo ) %>%
            count() %>% arrange(desc(n)) %>% head(20) %>% kable(col.names = c("Favorecido", "Tipo de documento","Quantidade") ,digits = 0, format.args = list(big.mark = ".", decimal.mark = ","))
```

### Sistema de origem

```{r}
docs_ug %>% group_by(doc_sistema_origem ) %>%
            count() %>% arrange(desc(n)) %>% kable(col.names = c("Sistema de origem","Quantidade") ,digits = 0, format.args = list(big.mark = ".", decimal.mark = ","))
```

### Data de lançamento do documento

```{r}
docs_ug %>% group_by(doc_lancado_por_data_acesso ) %>%
            count() %>% arrange(desc(n)) %>% head(10)%>% kable(col.names = c("Data de lançamento","Quantidade") ,digits = 0, format.args = list(big.mark = ".", decimal.mark = ","))
```

### Documentos emitidos no dia `r (docs_ug %>% group_by(doc_lancado_por_data_acesso ) %>% count() %>% arrange(desc(n)))[1,1]`

```{r}
docs_ug %>%
  filter(doc_lancado_por_data_acesso %in% 
           c((docs_ug %>% group_by(doc_lancado_por_data_acesso ) %>%
  count() %>% arrange(desc(n)))[1,1])) %>% group_by(doc_tipo_nome)%>%
  count() %>% arrange(desc(n)) %>% head(10)%>% kable(col.names = c("Tipo de documento","Quantidade") ,digits = 0, format.args = list(big.mark = ".", decimal.mark = ","))
```
