---
title: "SIAFI"
editor: visual
lang: "pt"
format:
  html:
    code-fold: true
    code-summary: "mostrar o código"
    code-overflow: wrap
execute:
  warning: false
  message: false
  error: false
  freeze: auto  # re-render only when source changes 
---

```{r}
#| warning: false
#| message: false
#| error: false
library(readxl)
library(tidyverse)
library(leaflet)
library(janitor)
library(lubridate)
library(tidyverse)
library(purrr)
library(knitr)
library(kableExtra)
library(DescTools)
library(zoo)
library(stringr)
library(data.table)
library(DT)
```

```{r}
`%notin%` <- Negate(`%in%`)

# formato dos numeros
myNumFmt <- as.fmt(digits=0, big.mark=".")

options(scipen = 999)
```

```{r}
lista_ugs_gestor <- read_excel("lista_ugs_gestor.xlsx") %>% clean_names()
```

```{r}
ug_selecionada <-  170166
```

## Lançamento Contábil

### Documento (como)

### Emitente UG (quem)

### Favorecido DOC (quem)

### Conta contábil (o que)

### Conta Corrente (o que)

### Emissão dia (quando)

### Doc valor (quanto)

### Documento de origem (qual vínculo)

## Consultar dados

### CONRAZAO (D)

### CONDOC (D)

### CONOR (D+1)

### BALANCETE (D+1)
